name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          override: true
          profile: minimal
          toolchain: stable

      - run: |
          export TAG_NAME=`echo ${{ github.ref }} | cut -d / -f 3`
          sed -i "s|^\(version = \"\).*\(\"  # VERSION_ANCHOR\)$|\1$TAG_NAME\2|" Cargo.toml
          cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
