name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          override: true
          profile: minimal
          toolchain: stable

      - id: prep
        run: |
          echo "base_key=${{ github.workflow }}-${{ github.job }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('Cargo.toml') }}" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ steps.prep.outputs.base_key }}-${{ github.ref }}
          restore-keys: |
            ${{ steps.prep.outputs.base_key }}-refs/heads/master
            ${{ steps.prep.outputs.base_key }}-

      - run: cargo fmt --all -- --check

      - run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable

      - id: prep
        run: |
          echo "base_key=${{ github.workflow }}-${{ github.job }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('Cargo.toml') }}" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ steps.prep.outputs.base_key }}-${{ github.ref }}
          restore-keys: |
            ${{ steps.prep.outputs.base_key }}-refs/heads/master
            ${{ steps.prep.outputs.base_key }}-

      - run: cargo test
